proxy:
  title: Landscape Toolbox Tools
  landing-page: /
  heartbeat-rate: 10000 # the user's browser will send a heartbeat call every heartbeat-rate milliseconds (10s as default)
  heartbeat-timeout: 60000 # if the server does not receive a heartbeat for heartbeat-timeout milliseconds, the relevant proxy will be released (60s as default)
  container-wait-time: 30000 # how long should we wait for the container to spin up (30s as default as this is enough for our Shiny apps)
  port: 8075
  authentication: none
  admin-groups: researchers
  users:
  - name: admin
    password: ldc~Admn1
    groups: researchers
  - name: user
    password: ldc~tst1
    groups: researchers

  container-backend: docker-swarm
#  container-backend: docker
  docker:
      internal-networking: true

  # Below is a list of Shiny apps and their config
  specs:
    - id: balanced-design-tool
      display-name: Balanced Design Tool
      container-cmd: ["R", "-e", "shiny::runApp('/home/docker/balanced-design-tool')"]
      container-image: landscapedatacommons/balanced-design-tool:4.2.1
      access-groups: [researchers]
      container-network: shiny-net
    - id: benchmark-exploration-tool
      display-name: Benchmark Exploration Tool
      container-cmd: ["R", "-e", "shiny::runApp('/home/docker/benchmark-exploration-tool')"]
      container-image: landscapedatacommons/benchmark-exploration-tool:4.2.1
      access-groups: [researchers]
      container-network: shiny-net
    - id: rangeland-indicator-calculator
      display-name: Rangeland Indicator Calculator
      container-cmd: ["R", "-e", "shiny::runApp('/home/docker/rangeland-indicator-calculator')"]
      container-image: landscapedatacommons/rangeland-indicator-calculator:4.2.2
      access-groups: [researchers]
      container-network: shiny-net

logging:
  file:
    name: shinyproxy.log
#    max-size: 50MB
#  level:
#    root: ERROR