version: "3.9"
services:
  shinyproxy-toolbox:
    image: landscapedatacommons/shinyproxy-toolbox:2.6.1
#    container_name: shinyproxy-toolbox
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip
#      placement:
#        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
    restart: on-failure
    networks:
      - shinyproxy-toolbox_default
    ports:
      - 8092:8080
    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
      - ./shinyproxy-logs/server:/log
      - ./shinyproxy-logs/container:/container-logs
      - ./application.yml:/opt/shinyproxy/application.yml
  benchmark-exploration-tool:
    image: landscapedatacommons/benchmark-exploration-tool:4.0.5
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip
#      placement:
#        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
#    container_name: benchmark-exploration-tool
    networks:
      - shinyproxy-toolbox_default
  balanced-design-tool:
    image: landscapedatacommons/balanced-design-tool:4.0.5
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip
#      placement:
#        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
#   container_name: balanced-design-tool
    networks:
      - shinyproxy-toolbox_default

networks:
  shinyproxy-toolbox_default:
    driver: overlay
    name: shinyproxy-toolbox_default